version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      PORT: 3000
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

volumes:
  redis-data: